apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: hyr-work
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  defaultBackend:
    service:
      name: nginx-deployment
      port:
        number: 80